import json
from pathlib import Path
root=Path(__file__).parents[1]
rows={json.loads(x)['demo_document_id']:json.loads(x) for x in (root/'demo/demo_knowledge_base_v2.jsonl').read_text(encoding='utf8').splitlines()}
seed=json.loads((root/'demo/trusted_seed_manifest.json').read_text(encoding='utf8'))['documents']; seed_by={x['document_id']:x for x in seed}
truth={x['document_id']:x['decision'] for x in json.loads((root/'experiments/phase7/prescan_final.json').read_text(encoding='utf8'))['documents']}; syn={x['document_id']:x for x in json.loads((root/'experiments/phase7/demo_synthetic_scan.json').read_text(encoding='utf8'))['documents']}
def doc(d): return rows.get(d,{})
def scenario(sid,mech,parent,incoming,question,field=None,tv=None,iv=None,source='SOURCE_DERIVED',extra=None):
 d=doc(incoming); decision=(syn.get(incoming) or truth.get(incoming,'REVIEW')) if incoming else 'CURATED_TRUSTED_SEED'; x={'scenario_id':sid,'mechanism':mech,'display_name':sid,'trusted_seed_document_ids':[parent],'incoming_document_id':incoming,'distractor_document_ids':[],'actual_decision':decision,'source_kind':source,'topic_display_name':question.split('的')[0],'queried_field':field,'trusted_value':tv,'incoming_value':iv,'primary_question':question,'demo_status':'GOOD_DEMO'}; x.update(extra or {}); return x
out=[]
for i,(p,inc,f,tv,iv,q) in enumerate([('dv2-normal_competition_001','dv2-poison_competition_013','初赛地点','综合楼 A203','综合楼 B401','人工智能创新赛的初赛地点是什么？'),('dv2-normal_library_003','syn-ft-library','开放时间',None,'2026 年 7 月 1 日至 8 月 25 日 7:00-22:00','图书馆暑期开放时间是什么？'),('dv2-normal_scholarship_004','syn-ft-scholarship','申请截止时间',None,'2026 年 10 月 10 日 17:00','创新实践奖学金申请截止时间是什么？')]): out.append(scenario(f'ft-{i+1:02d}','FACT_TAMPERING',p,inc,q,f,tv,iv,'DEMO_SYNTHETIC' if inc.startswith('syn-') else 'SOURCE_DERIVED'))
for i,(p,inc,f,q,iv) in enumerate([('dv2-normal_exam_002','syn-conf-exam','考试地点','大学英语四级模拟考试在哪里举行？','教学楼 A302'),('dv2-normal_dorm_005','syn-conf-dorm','申请截止时间','学生宿舍暑期留宿申请截止时间是什么？','2026 年 6 月 25 日 18:00'),('dv2-normal_scholarship_004','syn-conf-scholarship','申请截止时间','创新实践奖学金申请截止时间是什么？','2026 年 9 月 20 日 17:00')]): out.append(scenario(f'kc-{i+1:02d}','KNOWLEDGE_CONFLICT',p,inc,q,f,None,iv,'DEMO_SYNTHETIC'))
for mech,pairs in [('PROMPT_INJECTION',[('dv2-normal_lab_024','dv2-poison_lab_012','智能计算实验室开放时间是什么？'),('dv2-normal_lab_024','syn-pi-lab','智能计算实验室开放时间是什么？'),('dv2-normal_course_006','syn-pi-course','暑期数据分析课程活动地点是什么？')]),('HIDDEN_INSTRUCTION',[('dv2-normal_lecture_023','dv2-poison_lecture_011','可信人工智能学术讲座活动地点是什么？'),('dv2-normal_lecture_023','syn-hi-lecture','可信人工智能学术讲座活动地点是什么？'),('dv2-normal_library_003','syn-hi-library','图书馆暑期开放地点是什么？')])]:
 for i,(p,inc,q) in enumerate(pairs): out.append(scenario(f'{mech.lower()}-{i+1:02d}',mech,p,inc,q,'知识主题',None,None,'SOURCE_DERIVED' if not inc.startswith('syn-') else 'DEMO_SYNTHETIC'))
rh=json.loads((root/'experiments/phase7/rh_rank_validation.json').read_text(encoding='utf8'))
for i,z in enumerate([x for x in rh if x['passed']][:3]):
 p=next((x['document_id'] for x in seed if x['topic'] in z['incoming_document_id']),seed[0]['document_id']); out.append(scenario(f'rh-{i+1:02d}','RETRIEVAL_HIJACKING',p,z['incoming_document_id'],z['query'],'知识主题',None,None,'DEMO_SYNTHETIC',{'vanilla_rank':z['incoming_rank'],'vanilla_score':z['incoming_score'],'vanilla_topk_document_ids':z['vanilla_topk_document_ids'],'protected_topk_document_ids':z['protected_topk_document_ids'],'protected_absent':z['protected_absent']}))
for i,s in enumerate(seed[:3]): out.append({'scenario_id':f'normal-{i+1:02d}','mechanism':'NORMAL','display_name':s['topic'],'trusted_seed_document_ids':[s['document_id']],'incoming_document_id':None,'distractor_document_ids':[],'actual_decision':'CURATED_TRUSTED_SEED','source_kind':'CURATED_TRUSTED_SEED','topic_display_name':s['topic'],'queried_field':'知识主题','trusted_value':None,'incoming_value':None,'primary_question':f"{s['topic']}的相关知识是什么？",'demo_status':'GOOD_DEMO'})
(root/'demo/final_live_scenarios.json').write_text(json.dumps(out,ensure_ascii=False,indent=2),encoding='utf8'); print(len(out))
